### ISSUE TITLE
Issues running on Jetstream

### ISSUE THREAD

**Issue by zonca** [data-8/haas-infrastructure#2]
Reporting issues as I go installing this on a Jetstream Ubuntu 16.04 image Devel + Docker, version 1.6, small instance:

## Master setup

* `WARNING: docker version is greater than the most recently validated version. Docker version: 17.06.0-ce. Max validated version: 1.12` I guess I shouldn't worry about this, but wanted to note it here
* `kubeadm doesn't start due to /var/lib/kubelet`, fixed with `kubeadm reset`, see
 https://github.com/kubernetes/kubernetes/issues/37063#issuecomment-262979689
* `Error: could not find a ready tiller pod`, I guess `sleep 1m` was not enough, I commented out the first part of the script and reran `sudo ./init-master.bash`

Small issues, everything looks to be working fine!

## Worker setup

No issues on the commands

Should I do `curl localhost` on master again or on the worker? on the worker gives "Connection refused"

**Comment by zonca** [comment]
now trying to install Jupyterhub, hitting this issue: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/182

**Comment by yuvipanda** [comment]
Try making your config:

```
hub:
   db:
     type: sqlite-memory

singleuser:
   storage:
      type: none
```

That should let it start, and then we can figure out storage.

**Comment by zonca** [comment]
thanks @yuvipanda  it starts now, but there seems to be a networking issue:

```
sudo  kubectl --namespace=iris-jupyterhub get svc proxy-public
NAME           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
proxy-public   10.99.199.236   <pending>     80:32402/TCP   38m
```

**Comment by yuvipanda** [comment]
@aculich can you share your config for setting up the ingress?

**Comment by zonca** [comment]
@aculich can you please provide your config so I can continue my testing?

**Comment by zonca** [comment]
thanks @aculich for providing the configuration, I have now it running with HTTPS setting in the `config.yaml` of Jupyterhub:

```
ingress:
    enabled: true
    host: js-xxx-xxx.jetstream-cloud.org
    https:
      enabled: true
      type: "kube-lego"
```

Now, @yuvipanda do you have any suggestion on how to debug the storage issue?

**Comment by yuvipanda** [comment]
@zonca I've redone this now to work with latest kubeadm, so let me know if you can give this a shot again :)

**Comment by yuvipanda** [comment]
Going to close this one now!
